# Generated by Django 3.1 on 2020-09-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='virtual_server_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
