# Generated by Django 3.1 on 2020-09-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0002_auto_20200905_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='token_name',
            field=models.CharField(default='PFToken', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='data_store',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_endpoint',
            field=models.CharField(default='https://ebilling.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='default_relay_state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(choices=[('ASSERTION', 'Take value as is from the assertion.'), ('ALTER', 'Take value from the assertion and alter it.'), ('QUERY', 'Use values from the assertion to run a query.'), ('STRING', 'Add a static string to the token.')], default='ASSERTION', max_length=100),
        ),
    ]
