# Generated by Django 3.1 on 2020-09-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0003_auto_20200924_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='token_name',
        ),
        migrations.AddField(
            model_name='attribute',
            name='include_in_token',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='token_attribute_name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
