# Generated by Django 3.1 on 2020-09-25 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0004_auto_20200924_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_value',
        ),
    ]
