# Generated by Django 3.1 on 2020-09-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0005_remove_attribute_attribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attribute_value',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
