# Generated by Django 3.1 on 2020-09-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0006_attribute_attribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
