# Generated by Django 3.1 on 2020-09-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0007_attribute_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='_attribute_test_+', to='sp.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
