# Generated by Django 3.1 on 2020-09-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0008_auto_20200925_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='test',
        ),
        migrations.AddField(
            model_name='attribute',
            name='query_parameters',
            field=models.ManyToManyField(blank=True, related_name='_attribute_query_parameters_+', to='sp.Attribute'),
        ),
    ]
