# Generated by Django 3.1 on 2020-09-29 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0009_auto_20200925_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssertionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saml_attribute_name', models.CharField(help_text='The name of the attribute received in the SAML', max_length=100)),
                ('include_in_token', models.BooleanField(default=False, help_text='Should this be included in the token that is passed to the application?')),
                ('token_attribute_name', models.CharField(blank=True, help_text='The name to give the attribute value when adding it to the token that is passed to the application.', max_length=100, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp.destination')),
            ],
        ),
        migrations.CreateModel(
            name='TokenString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_in_token', models.BooleanField(default=True, help_text='Should this be included in the token that is passed to the application?')),
                ('token_attribute_name', models.CharField(help_text='The name to give this value when adding it to the token that is passed to the application.', max_length=100)),
                ('token_attribute_value', models.CharField(help_text='The name to give this value when adding it to the token that is passed to the application.', max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp.destination')),
            ],
        ),
        migrations.CreateModel(
            name='TokenQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, help_text='Use the SAML Attribute Values in a SQL query. Given an Attribute named SSO_ID, the correct\n                      syntax would be: \n\t\t SELECT username FROM users WHERE username  = %(SSO_ID)s \n                      \nThis syntax protects against SQL injection and is the only parameter substitution that should\n                      be used.', null=True)),
                ('include_in_token', models.BooleanField(default=True)),
                ('token_attribute_name', models.CharField(max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp.destination')),
                ('query_parameters', models.ManyToManyField(blank=True, to='sp.AssertionAttribute')),
            ],
        ),
    ]
