# Generated by Django 3.1 on 2020-11-30 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0011_auto_20201128_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='default_relay_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sp.relaystate'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_id',
            field=models.CharField(max_length=100),
        ),
    ]
