# Generated by Django 3.1 on 2020-12-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0013_auto_20201130_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('token_name', models.CharField(max_length=20)),
                ('token_location', models.CharField(choices=[('COOKIE', 'Send the token as a Cookie'), ('QUERY_STRING', 'Send the token as a Query String')], default='QUERY_STRING', max_length=50)),
                ('token_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='token_location',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='token_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='token_password',
        ),
        migrations.RemoveField(
            model_name='privatekey',
            name='entity',
        ),
        migrations.AddField(
            model_name='entity',
            name='private_keys',
            field=models.ManyToManyField(blank=True, null=True, to='sp.PrivateKey'),
        ),
        migrations.AlterField(
            model_name='relaystate',
            name='pattern_type',
            field=models.CharField(choices=[('SIMPLE', 'Simple URL Match with wildcard(*). (Example: https://*.hostname.com/uri* )'), ('REGEX', 'Python Regular Expression Match.')], default='SIMPLE', max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='token_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sp.tokenconfiguration'),
        ),
    ]
