# Generated by Django 3.1 on 2020-12-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0014_auto_20201208_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='private_keys',
            field=models.ManyToManyField(blank=True, to='sp.PrivateKey'),
        ),
    ]
