# Generated by Django 3.1 on 2021-01-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0015_auto_20201208_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_info',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='not_after',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='not_before',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject_name_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
