# Generated by Django 3.1 on 2021-01-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0017_certificate_common_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
