# Generated by Django 3.1 on 2021-01-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0018_auto_20210107_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='not_after',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='not_before',
        ),
    ]
