# Generated by Django 3.1 on 2021-01-22 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0019_auto_20210107_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('key', models.CharField(default='default', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='relaystate',
            name='data_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp.datastore'),
        ),
    ]
