# Generated by Django 3.1 on 2021-01-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0020_auto_20210122_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relaystate',
            name='data_store',
        ),
    ]
